on: 
  push:
    branches:
    - main
  
name: 🚀 Deploy website on push

jobs:
  
  web-deploy:

    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4

    - name: Use Node.js 18
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: 🔍 Check if secrets match known values
      run: |
        if [[ "${{ secrets.FTP_SERVER }}" == "ftp.todua.tech" ]]; then
          echo "FTP_SERVER matches the expected value";
        else
          echo "FTP_SERVER does not match the expected value";
        fi
        
        if [[ "${{ secrets.FTP_USERNAME }}" == "github@todua.tech" ]]; then
          echo "FTP_USERNAME matches the expected value";
        else
          echo "FTP_USERNAME does not match the expected value";
        fi
        
        if [[ "${{ secrets.FTP_PASSWORD }}" == "expected_password" ]]; then
          echo "FTP_PASSWORD matches the expected value";
        else
          echo "FTP_PASSWORD does not match the expected value";
        fi
